name: Code to pdf test
on: push
jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: cd  ${{ github.workspace }}
            - run: python3 setup.py install
            - run: cd tests; python3 test_cli.py
